"""Windowed live-safe PhaseC surge strategy optimizer.

Purpose:
Compare whether a long expanding training window or recent-market windows work
better for the second-stage surge scorer.  PhaseC remains frozen; this script
only trains live-safe surge rankers on the existing PhaseC candidate pool.

Selection discipline:
- Surge scorer OOF predictions for 2021-2025 are generated by year.
- Strategy ranking is selected using only OOF 2021-2025 metrics.
- 2026 Q1 / April / May are reported as forward validation.
"""

from __future__ import annotations

import json
import math
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(r"C:\Users\zzzzzzl\Desktop\subagent")
OUT_DIR = Path(r"E:\ashare_similarity_runtime\data\reports\prediction")
DOC_DIR = ROOT / "docs"
RUN_TAG = "phasec_windowed_surge_optimizer_20260520"

sys.path.insert(0, str(ROOT))
import scripts.run_phasec_live_safe_surge_optimizer_20260520 as core

WINDOW_POLICIES = {
    "expanding": None,
    "recent5": 5,
    "recent3": 3,
}

PERIODS = [
    ("stress_oof_2021_2022", "2021-01-01", "2022-12-31"),
    ("dev_oof_2023_2025", "2023-01-01", "2025-12-31"),
    ("q1_2026_forward", "2026-01-01", "2026-03-31"),
    ("apr_2026_forward", "2026-04-01", "2026-04-30"),
    ("may_2026_partial", "2026-05-01", "2026-05-31"),
]

RANK_COLS = [
    "raw_prob",
    "iso_prob",
    "safe_combo_score",
    "safe_surge5_score",
    "safe_limit10_score",
    "safe_pred_high_pct",
    "score_then_rsi6_low",
    "score_then_turnover",
    "score_then_amount_z",
]

EXIT_MODES = [
    "close",
    "tp3",
    "tp5",
    "tp7",
    "tp10",
    "sl1_tp5",
    "sl2_tp5",
    "sl2_tp7",
]

TOP_NS = [1, 2, 3, 4, 5, 6]

SEARCH_COLUMNS = [
    "date",
    "date_key",
    "month",
    "symbol",
    "name",
    "raw_prob",
    "iso_prob",
    "safe_surge5_score",
    "safe_limit10_score",
    "safe_pred_high_pct",
    "safe_combo_score",
    "score_source",
    "next_high_return_pct",
    "next_close_return_pct",
    "next_low_return_pct",
    "turnover",
    "close",
    "rsi_6",
    "volume_z_20",
    "amount_z_20",
    "range_pct",
    "close_position",
]


def policy_train_mask(df: pd.DataFrame, valid_year: int, years: int | None) -> np.ndarray:
    end = pd.Timestamp(f"{valid_year - 1}-12-31")
    if years is None:
        return (df["date"] <= end).to_numpy()
    # A 3-year window for valid_year=2025 should use 2022-2024, not 2023-2024.
    start = pd.Timestamp(f"{valid_year - years}-01-01")
    return ((df["date"] >= start) & (df["date"] <= end)).to_numpy()


def final_train_mask(df: pd.DataFrame, years: int | None) -> np.ndarray:
    end = pd.Timestamp("2025-12-31")
    if years is None:
        return (df["date"] <= end).to_numpy()
    # Final 3-year window for 2026 production is 2023-2025; 5-year is 2021-2025.
    start = pd.Timestamp(f"{2026 - years}-01-01")
    return ((df["date"] >= start) & (df["date"] <= end)).to_numpy()


def train_window_policy(df: pd.DataFrame, feature_cols: list[str], policy_name: str, years: int | None) -> tuple[pd.DataFrame, dict]:
    scored = df.copy()
    for col in ["safe_surge5_score", "safe_limit10_score", "safe_pred_high_pct", "safe_combo_score"]:
        scored[col] = np.nan
    scored["score_source"] = "unscored"

    x = scored[feature_cols].replace([np.inf, -np.inf], np.nan).fillna(0.0).astype(np.float32)
    folds = []
    for year in [2021, 2022, 2023, 2024, 2025]:
        train_mask = policy_train_mask(scored, year, years)
        valid_mask = (
            (scored["date"] >= pd.Timestamp(f"{year}-01-01"))
            & (scored["date"] <= pd.Timestamp(f"{year}-12-31"))
        ).to_numpy()
        train_idx = scored.index[train_mask].to_numpy()
        valid_idx = scored.index[valid_mask].to_numpy()
        if len(train_idx) < 30_000 or len(valid_idx) == 0:
            continue
        print(
            f"[{policy_name}] OOF {year}: train={len(train_idx):,}, valid={len(valid_idx):,}",
            flush=True,
        )
        models = core.fit_three_heads(x.loc[train_idx], scored.loc[train_idx], seed=3100 + year)
        core.add_score_columns(scored, x, models, valid_idx)
        scored.loc[valid_idx, "score_source"] = "oof"
        folds.append({"valid_year": year, "train_rows": int(len(train_idx)), "valid_rows": int(len(valid_idx))})

    fmask = final_train_mask(scored, years)
    forward_mask = (scored["date"] >= pd.Timestamp("2026-01-01")).to_numpy()
    fidx = scored.index[fmask].to_numpy()
    forward_idx = scored.index[forward_mask].to_numpy()
    print(f"[{policy_name}] Final scorer: train={len(fidx):,}, forward={len(forward_idx):,}", flush=True)
    models = core.fit_three_heads(x.loc[fidx], scored.loc[fidx], seed=9100 + (years or 99))
    if len(forward_idx):
        core.add_score_columns(scored, x, models, forward_idx)
        scored.loc[forward_idx, "score_source"] = "forward_final"

    diag = {
        "policy": policy_name,
        "years": years,
        "folds": folds,
        "final_train_rows": int(len(fidx)),
        "forward_rows": int(len(forward_idx)),
    }
    return scored, diag


def safe_num(df: pd.DataFrame, col: str, fill: float = 0.0) -> np.ndarray:
    return core.safe_num(df, col, fill)


def build_masks(df: pd.DataFrame, selection_df: pd.DataFrame) -> list[tuple[str, np.ndarray]]:
    raw = safe_num(df, "raw_prob")
    iso = safe_num(df, "iso_prob")
    combo = safe_num(df, "safe_combo_score", np.nan)
    s5 = safe_num(df, "safe_surge5_score", np.nan)
    pred_h = safe_num(df, "safe_pred_high_pct", np.nan)
    turnover = safe_num(df, "turnover")
    close = safe_num(df, "close")
    rsi = safe_num(df, "rsi_6", 50.0)
    vol = safe_num(df, "volume_z_20")
    amt = safe_num(df, "amount_z_20")
    rng = safe_num(df, "range_pct")
    cp = safe_num(df, "close_position", 0.5)

    bases: list[tuple[str, np.ndarray]] = []
    for thr in [0.70, 0.72, 0.73, 0.75, 0.78, 0.80]:
        bases.append((f"raw>={thr:.2f}", raw >= thr))
        bases.append((f"iso>={thr:.2f}", iso >= thr))
    for col, vals, label in [
        ("safe_combo_score", combo, "combo"),
        ("safe_surge5_score", s5, "s5"),
        ("safe_pred_high_pct", pred_h, "predH"),
    ]:
        ref = pd.to_numeric(selection_df[col], errors="coerce").replace([np.inf, -np.inf], np.nan).dropna()
        if len(ref) < 100:
            continue
        for q in [0.65, 0.75, 0.85, 0.90]:
            v = float(ref.quantile(q))
            bases.append((f"{label}_q{int(q * 100)}>={v:.4f}", vals >= v))

    refiners = [
        ("none", np.ones(len(df), dtype=bool)),
        ("turnover_3_20", (turnover >= 3) & (turnover <= 20)),
        ("turnover_5_30", (turnover >= 5) & (turnover <= 30)),
        ("close_3_80", (close >= 3) & (close <= 80)),
        ("close_5_80", (close >= 5) & (close <= 80)),
        ("volume_z>=0", vol >= 0),
        ("amount_z>=0", amt >= 0),
        ("rsi6<=55", rsi <= 55),
        ("rsi6<=45", rsi <= 45),
        ("range>=2", rng >= 2),
        ("close_pos>=0.55", cp >= 0.55),
        ("t5_30_amt0", (turnover >= 5) & (turnover <= 30) & (amt >= 0)),
        ("t5_30_vol0", (turnover >= 5) & (turnover <= 30) & (vol >= 0)),
        ("t5_30_rsi55", (turnover >= 5) & (turnover <= 30) & (rsi <= 55)),
    ]

    out: list[tuple[str, np.ndarray]] = []
    seen = set()
    for bname, bmask in bases:
        for rname, rmask in refiners:
            name = bname if rname == "none" else f"{bname}|{rname}"
            if name in seen:
                continue
            seen.add(name)
            mask = bmask & rmask
            if int(mask.sum()) >= 80:
                out.append((name, mask))
    return out


def rank_frame(df: pd.DataFrame, mask: np.ndarray, rank_col: str) -> pd.DataFrame:
    sub = df.loc[mask, [c for c in SEARCH_COLUMNS if c in df.columns]].copy()
    if sub.empty:
        return sub
    if rank_col == "score_then_rsi6_low":
        sub[rank_col] = safe_num(sub, "safe_combo_score") * 10_000 - safe_num(sub, "rsi_6", 50.0)
    elif rank_col == "score_then_turnover":
        sub[rank_col] = safe_num(sub, "safe_combo_score") * 10_000 + safe_num(sub, "turnover")
    elif rank_col == "score_then_amount_z":
        sub[rank_col] = safe_num(sub, "safe_combo_score") * 10_000 + safe_num(sub, "amount_z_20")
    sub = sub.sort_values(["date_key", rank_col, "raw_prob"], ascending=[True, False, False])
    sub["daily_rank"] = sub.groupby("date_key").cumcount() + 1
    return sub


def period_mask(df: pd.DataFrame, start: str, end: str) -> np.ndarray:
    return core.period_mask(df, start, end)


def eval_selected(
    ranked: pd.DataFrame,
    full_period_mask: np.ndarray,
    top_n: int,
    exit_mode: str,
    min_days: int = 4,
) -> dict | None:
    if ranked.empty:
        return None
    sub = ranked.loc[full_period_mask[ranked.index]]
    return core.evaluate_selected(sub, top_n, exit_mode, min_days=min_days)


def strict_score(row: dict) -> float:
    dev = row["dev_oof_2023_2025"]
    stress = row["stress_oof_2021_2022"]
    if dev["signal_days"] < 60 or dev["tickets"] < 60:
        return -1e9
    score = 0.0
    score += min(dev["total_return_pct"], 2500) * 0.18
    score += dev["avg_daily_return_pct"] * 100
    score += dev["daily_win_rate"] * 140
    score += dev["high5_rate"] * 70
    score += (dev["sharpe"] or 0) * 12
    score += max(stress["total_return_pct"], -800) * 0.04
    score += stress["daily_win_rate"] * 45
    score -= abs(min(dev["max_daily_loss_pct"], 0)) * 4
    return round(float(score), 4)


def current_confirm_score(row: dict) -> float:
    q1 = row["q1_2026_forward"]
    apr = row["apr_2026_forward"]
    may = row["may_2026_partial"]
    return round(
        row["strict_score"]
        + q1["total_return_pct"] * 0.8
        + apr["total_return_pct"] * 1.2
        + may["total_return_pct"] * 0.6
        + q1["daily_win_rate"] * 40
        + apr["daily_win_rate"] * 50,
        4,
    )


def search_policy(scored: pd.DataFrame, policy_name: str) -> tuple[list[dict], pd.DataFrame]:
    search_df = scored[[c for c in SEARCH_COLUMNS if c in scored.columns]].copy().reset_index(drop=True)
    selection_mask = (
        period_mask(search_df, "2023-01-01", "2025-12-31")
        & (search_df["score_source"].to_numpy() == "oof")
    )
    selection_df = search_df.loc[selection_mask]
    masks = build_masks(search_df, selection_df)
    period_specs = [(name, period_mask(search_df, start, end)) for name, start, end in PERIODS]
    rows: list[dict] = []
    t0 = time.time()
    print(f"[{policy_name}] Search masks={len(masks)}, ranks={len(RANK_COLS)}", flush=True)
    for mi, (mname, mask) in enumerate(masks, 1):
        for rank_col in RANK_COLS:
            if rank_col not in search_df.columns and not rank_col.startswith("score_then_"):
                continue
            ranked = rank_frame(search_df, mask, rank_col)
            if ranked.empty:
                continue
            for top_n in TOP_NS:
                # Cap before exit loops to keep evaluation cheap.
                ranked_top = ranked[ranked["daily_rank"] <= top_n]
                for exit_mode in EXIT_MODES:
                    row = {"policy": policy_name, "mask": mname, "rank_col": rank_col, "top_n": top_n, "exit_mode": exit_mode}
                    ok = True
                    for pname, pmask in period_specs:
                        # May 2026 is a partial, low-day report window. Do not let
                        # it eliminate otherwise valid strategies during selection.
                        min_days = 1 if pname == "may_2026_partial" else 4
                        ev = eval_selected(ranked_top, pmask, top_n, exit_mode, min_days=min_days)
                        if ev is None:
                            ok = False
                            break
                        row[pname] = ev
                    if not ok:
                        continue
                    row["strict_score"] = strict_score(row)
                    row["current_confirm_score"] = current_confirm_score(row)
                    rows.append(row)
        if mi % 30 == 0:
            print(f"[{policy_name}] masks {mi}/{len(masks)}, rows={len(rows):,}, elapsed={time.time()-t0:.0f}s", flush=True)
    rows.sort(key=lambda r: r["strict_score"], reverse=True)
    return rows[:200], search_df


def monthly_breakdown(search_df: pd.DataFrame, rule: dict) -> list[dict]:
    selection_mask = period_mask(search_df, "2023-01-01", "2025-12-31")
    masks = build_masks(search_df, search_df.loc[selection_mask])
    mask_map = {name: mask for name, mask in masks}
    ranked = rank_frame(search_df, mask_map[rule["mask"]], rule["rank_col"])
    picked = ranked[ranked["daily_rank"] <= int(rule["top_n"])].copy()
    picked["realized_return_pct"] = core.compute_exit(picked, rule["exit_mode"])
    rows = []
    for month, sub in picked.groupby("month"):
        daily = sub.groupby("date_key")["realized_return_pct"].mean().to_numpy()
        rows.append(
            {
                "month": month,
                "days": int(len(daily)),
                "tickets": int(len(sub)),
                "return_pct": round(core.pct_prod(daily), 2),
                "daily_win_rate": round(float((daily > 0).mean()), 4) if len(daily) else None,
                "high5_rate": round(float((sub["next_high_return_pct"] >= 5).mean()), 4) if len(sub) else None,
            }
        )
    return rows


def write_outputs(results: dict, scored_frames: dict, feature_cols: list[str], diags: dict) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    DOC_DIR.mkdir(parents=True, exist_ok=True)
    json_path = OUT_DIR / f"{RUN_TAG}.json"
    rules_path = OUT_DIR / f"{RUN_TAG}_top_rules.csv"
    md_path = DOC_DIR / f"{RUN_TAG}.md"

    flat = []
    best_by_policy = {}
    monthly_by_policy = {}
    for policy, rows in results.items():
        for row in rows:
            flat.append(row)
        if rows:
            best_by_policy[policy] = rows[0]
            monthly_by_policy[policy] = monthly_breakdown(scored_frames[policy], rows[0])
    pd.DataFrame(flat).to_csv(rules_path, index=False, encoding="utf-8-sig")
    payload = {
        "run_tag": RUN_TAG,
        "feature_count": len(feature_cols),
        "feature_cols": feature_cols,
        "forbidden_selected": [c for c in feature_cols if core.is_forbidden(c)],
        "window_policy_diags": diags,
        "best_by_policy": best_by_policy,
        "monthly_by_policy": monthly_by_policy,
        "notes": [
            "Strategy selection uses 2021-2025 OOF only.",
            "2026 windows are forward validation only.",
            "tp/sl exits use daily high/low idealization and need minute-order replay before live execution.",
        ],
    }
    json_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")

    lines = [
        f"# Windowed PhaseC Live-Safe Surge Optimizer - {RUN_TAG}",
        "",
        "## Guardrails",
        "",
        "- PhaseC bundle is frozen; no PhaseC retrain here.",
        "- Surge scorer features are live-safe only.",
        "- Window policies compared: expanding, recent5, recent3.",
        "- Strategy selection uses 2021-2025 rolling OOF metrics; Q1/April/May 2026 are validation reports.",
        "- Stop/take-profit modes are high/low idealized and require minute replay before deployment.",
        "",
        "## Best By Window",
        "",
    ]
    for policy, best in best_by_policy.items():
        lines.extend(
            [
                f"### {policy}",
                "",
                f"- mask: `{best['mask']}`",
                f"- rank: `{best['rank_col']}`",
                f"- top_n: `{best['top_n']}`",
                f"- exit: `{best['exit_mode']}`",
                f"- strict_score: `{best['strict_score']}`",
                f"- current_confirm_score: `{best['current_confirm_score']}`",
                "",
            ]
        )
        for pname, *_ in PERIODS:
            ev = best[pname]
            lines.append(
                f"- {pname}: return={ev['total_return_pct']}%, days={ev['signal_days']}, "
                f"daily_win={ev['daily_win_rate']}, high5={ev['high5_rate']}, "
                f"limit10={ev['limit10_rate']}, max_loss={ev['max_daily_loss_pct']}%"
            )
        lines.append("")
    lines.extend(["## Files", "", f"- JSON: `{json_path}`", f"- Rules CSV: `{rules_path}`"])
    md_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {json_path}", flush=True)
    print(f"Wrote {md_path}", flush=True)


def main() -> None:
    t0 = time.time()
    base_df = core.load_pool()
    feature_cols = core.choose_live_safe_features(base_df)
    forbidden = [c for c in feature_cols if core.is_forbidden(c)]
    if forbidden:
        raise RuntimeError(f"Forbidden selected: {forbidden}")
    print(f"Live-safe feature count: {len(feature_cols)}", flush=True)

    results = {}
    scored_frames = {}
    diags = {}
    for policy, years in WINDOW_POLICIES.items():
        scored, diag = train_window_policy(base_df, feature_cols, policy, years)
        rows, search_df = search_policy(scored, policy)
        results[policy] = rows
        scored_frames[policy] = search_df
        diags[policy] = diag
        if rows:
            print(f"[{policy}] Best: {json.dumps(rows[0], ensure_ascii=False)[:1600]}", flush=True)
    write_outputs(results, scored_frames, feature_cols, diags)
    print(f"Done in {(time.time() - t0) / 60:.1f} min", flush=True)


if __name__ == "__main__":
    main()
